Added lf-select, slightly modified automtp

diff --git a/automtp b/automtp
--- a/automtp
+++ b/automtp
@@ -1,21 +1,37 @@
 #!/bin/bash
 # Koonix 2020-08-19
 
+# Functions
+# Delete temp files
+cleanup() { \
+find -P /tmp -maxdepth 1 -name automtpmount\* -delete > /dev/null 2>&1
+}
+# Cleanup and exit
+cleanup_and_exit() { \
+    cleanup
+    echo; echo "Exiting..."
+    exit 0
+}
+# Cleanup and exit upon receiving SIGINT
+trap "cleanup_and_exit" SIGINT
+
+
 # Check if the user wants to proceed
-echo "All MTP devices will now be unmounted."
+echo "All MTP devices will now be UNMOUNTED;"
 read -p "Press enter to proceed..."
 
-# Intercept abort signals from jmtpfs and do not show them.
+# Intercept ugly abort signals from jmtpfs and do not show them.
 trap "" SIGABRT
 
-# Clear all the leftover mtp crap
+# Clean all the leftover mtp directory crap from previous runs
 echo; echo "Cleaning previous mount points..."
 sudo umount "${HOME}"/mount/* > /dev/null 2>&1
 rmdir "${HOME}"/mount/* > /dev/null 2>&1
 
-# Query mtp devices to assert the precense of this master device (lol)
+# Query mtp devices to assert the precense of this master device (the linguistics tho lol)
 echo; echo "Pinging all available devices..."
 jmtpfs > /dev/null 2>&1
+jmtpfs -l > /dev/null 2>&1
 
 
 # Make temp files
@@ -25,7 +41,7 @@ devices_id_list=$(mktemp /tmp/automtpmount.XXXXXXXX)
 devices_name_list=$(mktemp /tmp/automtpmount.XXXXXXXX)
 
 
-# Build some lists of devices
+# Build some lists of available/detected devices
 echo "Building list of devices..."
 jmtpfs -l | awk 'f;/Available/ {f=1}' | awk '!seen[$0]++'         > "$devices_info_list"
 awk -F  ", " '{print $6}'                    "$devices_info_list" > "$devices_vendor_list"
@@ -34,7 +50,7 @@ jmtpfs -l | awk '/Device/ {print substr($0, index($0, $8))}'      > "$devices_na
 
 
 # Exit if the list of devices is empty (no device found)
-if [[ ! -s $devices_info_list ]]
+if [ ! -s "$devices_info_list" ]
 then
     echo
     echo "No devices found!"
@@ -56,7 +72,7 @@ echo "~~ ~~ ~~ ~~ ~~ ~~"
 
 
 # Check if the user wants to proceed
-echo; echo "All detected devices will now be mounted."
+echo; echo "All detected devices will now be MOUNTED;"
 read -p "Press enter to proceed..."
 
 
@@ -65,7 +81,7 @@ devices_count=$(wc -l < "$devices_info_list")
 
 # Loop over all devices and mount them
 i=1
-while [[ $i -le $devices_count ]]
+while [ "$i" -le "$devices_count" ]
 do
 
     device_vendor=$(sed "${i}q;d" "$devices_vendor_list")
@@ -87,8 +103,9 @@ do
 done
 
 
-# Delete temp files
-find -P /tmp -maxdepth 1 -name automtpmount\* -delete > /dev/null 2>&1
+# Do the cleaning
+cleanup
 
 # Prompt the exit
 echo; read -p "Done. Press enter to exit..."
+exit 0
