Improved bashmtp, bashftp, Cleaned up all the scripts, other changes

diff --git a/mount/bashmtp b/mount/bashmtp
--- a/mount/bashmtp
+++ b/mount/bashmtp
@@ -1,57 +1,130 @@
 #!/bin/bash
+# My android mtp mounting script, using jmtpfs. so make sure youu install that.
+# Because all the other methods suck.
+# So ofcourse I had to write my fucking own.
 
 # Config
-ftp_ip="192.168.1.15:9999"
+top_level_mount_dir="$HOME/Mount/MTP"
 
-main() {
-    # Big boy ethernal while loop
-    while true; do
-
-    clear
-    helper_text
-    read -p "Command: " entered_command
-
-    case "$entered_command" in
-        m)
-            ftp_mount
-            continue
-            ;;
-        u)
-            ftp_unmount
-            continue
-            ;;
-        q)
-            exit 0
-            ;;
-        *)
-            command_output="Command invalid"
-            ;;
-    esac
-    done
+# Functions
+# Delete temp files
+cleanup() {
+    find -P /tmp -maxdepth 1 -name automtpmount\* -delete > /dev/null 2>&1
 }
-
-ftp_mount() {
-    command_output="$(\
-        2>&1 curlftpfs -o utf8 "ftp://${ftp_ip}" ~/Mount/FTP &&\
-        echo "FTP Mounted")"
+# Cleanup and exit
+cleanup_and_exit() {
+    cleanup
+    echo; echo "Exiting..."
+    exit 0
 }
+# Cleanup and exit upon receiving SIGINT
+trap "cleanup_and_exit" SIGINT
 
-ftp_unmount() {
-    command_output="$(\
-        2>&1 fusermount -u ~/Mount/FTP &&\
-        echo "FTP UnMounted")"
-}
 
-helper_text() {
-echo -e "${command_output}
+# Check if the user wants to proceed
+echo "All MTP devices will now be UnMounted;"
+read -p "Press enter to proceed..."
 
-━━━━━━━━━━━━ Commands ━━━━━━━━━━━
+# Intercept ugly abort signals from jmtpfs and do not show them.
+trap "" SIGABRT
 
-m: mount    u: unmount    q: quit
+# Clean all the leftover mtp directory crap from previous runs
+echo; echo "Cleaning previous mount points..."
+sudo umount "$top_level_mount_dir"/* > /dev/null 2>&1
+rmdir "$top_level_mount_dir"/* > /dev/null 2>&1
 
-━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-"
-}
+echo -e "\n    All devices UnMounted successfully."
 
-# Run the main function
-main; exit
+echo; echo "Now attempting to mount the connected devices."
+# Query mtp devices to assert the precense of
+# this master device (the linguistics tho lol)
+echo "Pinging all available devices..."
+jmtpfs > /dev/null 2>&1
+jmtpfs -l > /dev/null 2>&1
+
+
+# Make temp files
+devices_info_list=$(mktemp /tmp/automtpmount.XXXXXXXX)
+devices_vendor_list=$(mktemp /tmp/automtpmount.XXXXXXXX)
+devices_id_list=$(mktemp /tmp/automtpmount.XXXXXXXX)
+devices_name_list=$(mktemp /tmp/automtpmount.XXXXXXXX)
+
+
+# Build some lists of available/detected devices
+echo "Building list of devices..."
+jmtpfs -l | awk 'f;/Available/ {f=1}' |
+    awk '!seen[$0]++'                          > "$devices_info_list"
+
+awk -F ", " '{print $6}'\
+    "$devices_info_list"                       > "$devices_vendor_list"
+
+awk '{print $1 substr($2, 1, length($2)-1)}'\
+    "$devices_info_list"                       > "$devices_id_list"
+
+jmtpfs -l | awk '/Device/ \
+    {print substr($0, index($0, $8))}'         > "$devices_name_list"
+
+
+# Exit if the list of devices is empty (no device found)
+if [ ! -s "$devices_info_list" ]
+then
+    echo
+    echo "    No devices found!"
+    echo
+    read -p "Press enter to exit..."
+    exit 1
+fi
+
+
+# List detected devices
+echo; echo "    ~~ ~~ ~~ ~~ ~~ ~~"
+echo "    Detected devices:"
+echo; echo -n "    "; cat "$devices_name_list"
+echo "    ~~ ~~ ~~ ~~ ~~ ~~"
+
+echo; echo "    ~~ ~~ ~~ ~~ ~~ ~~"
+echo "    Device vendors:"
+echo; echo -n "    "; cat "$devices_vendor_list"
+echo "    ~~ ~~ ~~ ~~ ~~ ~~"
+
+
+# Check if the user wants to proceed
+echo; echo "All detected devices will now be Mounted;"
+read -p "Press enter to proceed..."
+
+
+# Count number of devices
+devices_count=$(wc -l < "$devices_info_list")
+
+# Loop over all devices and mount them
+i=1
+while [ "$i" -le "$devices_count" ]
+do
+
+    device_vendor=$(sed "${i}q;d" "$devices_vendor_list")
+    device_id=$(sed "${i}q;d" "$devices_id_list")
+    device_name=$(sed "${i}q;d" "$devices_name_list")
+
+    device_id_no_comma=${device_id//,}
+    mount_dir_name="${device_vendor}${device_id_no_comma}"
+    mount_dir="${top_level_mount_dir}/${mount_dir_name}"
+    mkdir -p "$mount_dir"
+
+    echo
+    echo "    ~~ ~~ ~~ ~~ ~~ ~~"
+    echo "    Mounting: $device_name"
+    echo "    As:       $mount_dir_name"
+    echo "    ~~ ~~ ~~ ~~ ~~ ~~"
+
+    jmtpfs -device="$device_id" "$mount_dir" -o auto_unmount > /dev/null 2>&1
+
+    ((i = i + 1))
+done
+
+
+# Do the cleaning
+cleanup
+
+# Prompt the exit
+echo -e "\n    Done.\n"; read -p "Press enter to exit..."
+exit 0
diff --git a/other/mv-cookie b/other/mv-cookie
--- a/other/mv-cookie
+++ b/other/mv-cookie
@@ -1,17 +1,13 @@
 #!/bin/sh
+# Move the youtube cookie I extracted [ from firefox via an addon ] to it's
+# appropriate place, to be used by my youtube-dl scripts.
 
-src="/mnt/drives/d/downloads/artix/firefox/cookies.txt"
+dest="$XDG_DATA_HOME/ytdl-cookies/youtube.cuck"
+dl="/mnt/drives/d/downloads/artix/firefox"
+src="$dl/cookies.txt"
 
-[ ! -r "$src" ] &&\
-    src="/mnt/drives/d/downloads/artix/firefox/cookie/cookies.txt"
-
-[ ! -r "$src" ] &&\
-    echo "cookie file not found" && exit 1
-
-dest="${HOME}/.local/share/ytdl-cookies/youtube.cookie"
+[ ! -r "$src" ] && src="$dl/cookie/cookies.txt"
+[ ! -r "$src" ] && echo "cookie file not found" && exit 1
 
 mv -fv "$src" "$dest" || echo "mv error"
-
 chmod -v a-x "$dest" || echo "chmod error"
-
-exit 0
