Added eagle eye-saving script, implemented dwm statuscolors to sucklessbar, other changes

diff --git a/stream-player/play b/stream-player/play
--- a/stream-player/play
+++ b/stream-player/play
@@ -1,5 +1,7 @@
 #!/bin/bash
 #
+#                  S T R E A M    P L A Y E R
+#
 # Launch a stream in mpv via youtube-dl via tor via polipo proxy.
 #
 # Usage:
@@ -15,8 +17,8 @@
 #         play -k
 #         play --kill
 
-# Path to playrc file
-playrc_file="${HOME}/.config/play/playrc"
+# Path to list of streams
+stream_list="${HOME}/.config/stream-player/stream.list"
 
 # Main function
 main() {
@@ -60,6 +62,8 @@ play_stream_in() {
         echo "playing: $stream_name"
         echo "link: $stream_url"
 
+        notify-send "  Stream Player" "Loading stream ${stream_name}..."
+
         [ "$2" = "background" ] && stream_back "$stream_url" && return
 
         stream_fore "$stream_url"
@@ -87,14 +91,14 @@ stream_kill() {
     killall -q polipo
 }
 
-# Lookup a stream name in .config/play/playrc and return the stream url
+# Lookup a stream name in stream list and return the stream url
 stream_name_to_url() {
 
     local stream_name="$1";
 
     [ -z "$stream_name" ] && return
 
-    local stream_url="$(awk 'BEGIN{FS=OFS="#"}; {print $1}' "$playrc_file" |\
+    local stream_url="$(awk 'BEGIN{FS=OFS="#"}; {print $1}' "$stream_list" |\
         awk NF | awk -v pattern="$stream_name" '$1~pattern {print $2}')"
 
     echo "$stream_url"
@@ -104,7 +108,9 @@ stream_name_to_url() {
 check_stream_url() {
         local stream_url="$1"
         [ -z "$stream_url" ] &&\
-            echo "error: given stream name doesn't exist in playrc" >&1 &&\
+            echo "error: given stream doesn't exist in stream.list" >&1 &&\
+            notify-send "  Stream Player"\
+            "Error: Given stream doesn't exist in stream.list" &&\
             return 1
         return 0
 }
@@ -112,12 +118,14 @@ check_stream_url() {
 # Check if the given file is readable/accessible
 check_readable() {
     [ ! -r "$1" ] &&\
-        echo "error: playrc file doesn't exist or unreadable" >&1 &&\
+        echo "error: stream.list file doesn't exist or unreadable" >&1 &&\
+        notify-send "  Stream Player"\
+        "Error: stream.list file doesn't exist or unreadable" &&\
         return 1
     return 0
 }
 
-check_readable "$playrc_file" || exit
+check_readable "$stream_list" || exit
 
 # Intercept SIGINT and SIGTERM
 trap stream_kill 2
